---
title: "Data Viz of ANES data and Google Trends for GOV 404"
author: "Zoe Meers"
date: "4/16/2017"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plyr)
library(tidyverse)
#install.packages("srvyr")
library(srvyr)
library(haven)
#install.packages("likert")
library(likert)
library(extrafont)
```

```{r, warnings=FALSE, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
library(Hmisc)
anes_sav <- spss.get("~/Downloads/anes_timeseries_2016_sav-2/anes_timeseries_2016.sav", use.value.labels=TRUE, to.data.frame=TRUE, reencode = NA)
```
```{r, include=FALSE, echo=FALSE}
str(anes_sav)
```

```{r, include=FALSE, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
anes_sav[ anes_sav == "-6. No post-election interview"] <- NA
anes_sav[ anes_sav == "-7. No post data, deleted due to incomplete IW"] <- NA
anes_sav[ anes_sav == "-1. INAP, voter (11 in V161132)/ late placement (20,21 in V161132)"] <- NA
anes_sav[ anes_sav == "-1. INAP, birthyear missing"] <- NA
```
```{r, include=FALSE, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
anes_sav[ anes_sav == "-1. INAP, -8,-9 in V161140a/ -8,-9 in V161140"] <- NA
anes_sav[ anes_sav == "-1. Inap, 0,-8,-9 in V161008"] <- NA
anes_sav[ anes_sav == "-9. RF (-9) in V161155 (FTF only)/ -9 in V161156 or V161157"] <- NA
anes_sav[ anes_sav == "-8. DK (-8) in V161156 or V161157 (FTF only)"] <- NA
anes_sav[ anes_sav == "-9. RF (-9) in V161155 (FTF only)/ -9 in V161156"] <- NA

```


```{r, message=FALSE, include=FALSE, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
anes_sav %>%
  as_survey_design(ids=1, weights=V160102, strata=V160201)
```


```{r, include=FALSE, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
#subsetting data
anes_clean <- anes_sav %>%
  dplyr::select(V160001,V162072,V162073a,V162073b,V162074a,V162074b,V162075a,V162075b,V162076a,V162076b,V161267,V161267x,V161270,V161009,V161158x,V161146,V161140x,V161133,V161126,V161128,V161129,V161130,V161131,V161112,V161009,V161003,V161008,V161127,V161128,V161129,V161130,V161131,V161178,V161179,V161180,V161181,V161182,V161183,V161184,V161185,V161186,V161189,V161190,V161191,V161198,V161199,V161200,V161201,V161202,V161203)

```

```{r, include=FALSE, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
anes_clean <-plyr::rename(anes_clean,
                     c(V160001="ID",
                 V162072="Joe Biden",
                 V162073a="Paul Ryan",
                 V162074a="Angela Merkel",
                 V162075a="Vladimir Putin",
                 V162076b = "John Roberts",
                 V161267 = "age",
                 V161267x = "age_group",
                 V161270 = "education",
                 V161009 = "media_pay_attention",
                 V161158x = "party_ID",
                 V161146 = "predict_president",
                 V161140x = "economy_better_worse",
                 V161133 = "likely_voter",
                 V161126 = "7pt_liberal_conservative_placement",
                 V161128 = "7pt_liberal_conservative_dem_cand",
                 V161129 = "7pt_liberal_conservative_rep_cand",
                 V161130 = "7pt_liberal_conservatice_dem_party",
                 V161131 = "7pt_liberal_conservative_rep_party",
                 V161112 = "health_insurance_yes_no",
                 V161003 = "pay_attention_politics",
                 V161008 = "days_consuming_media")
                
                 )
```


```{r, include=FALSE, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
str(anes_clean)
```
```{r, include=FALSE, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
anes_clean <- droplevels(anes_clean)
```

```{r, include=FALSE, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
anes_clean[ anes_clean == "-6. No post-election interview"] <- NA
anes_clean[ anes_clean == "-7. No post data, deleted due to incomplete IW"] <- NA
```


```{r, include=FALSE, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
#likert(anes_clean$`7pt_liberal_conservatice_dem_party`)
library(likert)
ID_president <- anes_clean %>%
  dplyr::select(party_ID, predict_president)
str(ID_president$predict_president)
head(ID_president$predict_president)
head(anes_clean$education)
```


```{r, include=FALSE,echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
items_OR <- subset(anes_clean, select=c("Paul Ryan","John Roberts","Angela Merkel","Vladimir Putin","Joe Biden"))
```


```{r, include=FALSE, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
abc<- likert::likert(items_OR, grouping=anes_clean$party_ID)
bce <- likert::likert(items_OR, grouping=anes_clean$age_group)
def <- likert::likert(items_OR)
```



```{r, include=FALSE, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
library(HH)
library(RColorBrewer)
my.settings <- list(
  superpose.polygon=list(border="grey"),
  strip.background=list(col="white"),
  strip.border=list(col="black"),
  brewer.pal.likert(3,"Blues","Blue1")
)

```


```{r fig.height=5, fig.width=5, echo=FALSE}
plot.def <- HH::plot.likert(def,  layout=c(1,1),
    positive.order=TRUE, main="The Ability of Americans to Recognise\n the Office of Five Political Figures",
   ylab=NULL, 
    par.strip.text=list(cex=1, lines=1),
    par.settings=my.settings, key.border.white=TRUE)
plot.def
```
```{r, fig.height=18, fig.width=5, echo=FALSE}
y<-HH::plot.likert(abc,  layout=c(1,7),
    positive.order=TRUE, main="The Ability of Americans, Divided\n by Ideology, to Recognise the Office\n of Five Political Figures",
   ylab=NULL, 
    par.strip.text=list(cex=1, lines=1),
    par.settings=my.settings, 
   key.border.white=TRUE)

y
```

```{r fig.height=30, fig.width=5, echo=FALSE}
plot.bce <- HH::plot.likert(bce,  layout=c(1,13),
    positive.order=TRUE, main="The Ability of Americans, Divided\n by Age, to Recognise the Office\n of Five Political Figures",
   ylab=NULL, 
    par.strip.text=list(cex=1, lines=1),
    par.settings=my.settings, key.border.white=TRUE)
plot.bce
```

```{r, include=FALSE, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
#devtools::install_github('PMassicotte/gtrendsR')
```
```{r, include=FALSE, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
library(gtrendsR)
library(dplyr)
```

```{r, include=FALSE, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
pl_trend <- gtrends(c("Joe Biden","John Roberts","Paul Ryan","Angela Merkel","Vladimir Putin"), geo="US", gprop="news")
```


```{r, include=FALSE, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
tdf <- pl_trend$interest_over_time
tdf_clipped <- tdf %>%
  filter(date > "2015-01-01" & date <"2016-11-30")
```
```{r, include=FALSE, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
library(reshape2)
mdf <- melt(tdf,id.vars=c("date"))
```


```{r, fig.width=15, warnings=FALSE, message=FALSE, echo=FALSE}
library(ggplot2)
library(extrafont)
library(RColorBrewer)

ggplot(data=tdf_clipped,aes(x=date,y=hits,color=keyword)) +
  geom_line(size=1.5)+ theme_light()+ 
  labs(title = "US Google News Trends During the Election Cycle", x="Date", y="Number of Hits") + theme(text=element_text(size=14,  family="Times New Roman")) + scale_x_datetime(date_breaks = "2 month") + scale_color_brewer(palette="Paired")
ggsave("gtrends.jpg", last_plot())
```

```{r, include=FALSE, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
election_trend <- gtrends(c("election","Congress","Supreme Court", "Germany", "Russia"), geo="US", gprop = "news")
```

```{r, include=FALSE, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
edf <- election_trend$interest_over_time
edf_clipped <- edf %>%
  filter(date > "2015-01-01" & date <"2016-11-30")
```

```{r, include=FALSE, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
library(reshape2)
mdf <- melt(edf,id.vars=c("date"))
```


```{r, fig.width=15, warning=FALSE, message=FALSE, echo=FALSE}
ggplot(data=edf_clipped,aes(x=date,y=hits,color=keyword)) +
  geom_line(size=1.5)+ theme_light() +
  labs(title = "US Google News Trends During the Election Cycle", x="Date", y="Number of Hits") + theme(text=element_text(size=14,  family="Times New Roman")) + scale_x_datetime(date_breaks = "2 month") + scale_color_brewer(palette="Paired")
ggsave("election_trends.jpg", last_plot())
```

